# config/criteria.yaml
criteria:
  - criterion_id: c001
    criterion_name: task_completion
    description: "Did the agent successfully accomplish what was asked?"
    rubric_file: config/rubrics/task_completion.md
    scale: 1-5

  - criterion_id: c002
    criterion_name: tool_use_efficiency
    description: "Did the agent use tools appropriately without redundant calls?"
    rubric_file: config/rubrics/tool_use_efficiency.md
    scale: 1-5
    
#  - criterion_id: c003
#    criterion_name: verbosity
#    description: "Did the agent use tools appropriately without redundant calls?"
#    rubric_file: config/rubrics/tool_use_efficiency.md
#    scale: 1-5